-module(codegen_tests).

-include_lib("eunit/include/eunit.hrl").

-import_record(marmot, [typed_query, field]).

get_user_query() ->
    {module, marmot} = code:ensure_loaded(marmot),
    #typed_query{
        input_file_name = "get_user.sql",
        starting_line = 1,
        root_name = "get_user",
        content = ~"-- Get a user.\nselect id, name from users where id = $1",
        params = [int],
        returns = [
            #field{identifier = id, type = int},
            #field{identifier = name, type = {option, bit_array}}
        ],
        doc = [~"Get a user."]
    }.

ping_query() ->
    {module, marmot} = code:ensure_loaded(marmot),
    #typed_query{
        input_file_name = "ping.sql",
        starting_line = 1,
        root_name = "ping",
        content = ~"select 1",
        params = [],
        returns = [],
        doc = []
    }.

render_single_column_test() ->
    {module, marmot} = code:ensure_loaded(marmot),
    Query = #typed_query{
        input_file_name = "one.sql",
        starting_line = 1,
        root_name = "one",
        content = ~"select 1 as one",
        params = [],
        returns = [#field{identifier = one, type = int}],
        doc = []
    },
    {ok, Forms} = codegen:forms(one_sql, [Query]),
    Expected =
        ~"""
        -module(one_sql).

        -export([one/0, one_sql/0]).

        -record #one_row{one :: integer()}.

        -export_record([one_row]).

        one_sql() -> <<"select 1 as one"/utf8>>.

        -spec one() -> {ok, non_neg_integer(), [#one_row{}]} | {error, term()}.

        one() ->
            Opts = #{decode_opts =>
                         [{return_rows_as_maps, false},
                          {column_name_as_atom, false},
                          {decode_fun, undefined}]},
            case pgo:query(one_sql(), [], Opts) of
                #{num_rows := N, rows := Rows} ->
                    try {ok, N, [decode_one_row(R) || R <- Rows]} catch
                        {marmot_decode_error, Reason} -> {error, Reason}
                    end;
                {error, _} = E -> E
            end.

        decode_one_row({C1}) -> #one_row{one = C1}.
        """,
    ?assertEqual(Expected, codegen:render(Forms)).

compile_one_param_one_column_test() ->
    {ok, Forms} = codegen:forms(get_user_sql, [get_user_query()]),
    ?assertMatch({ok, _, _}, compile:forms(Forms, [return_errors])).

compile_option_column_test() ->
    {module, marmot} = code:ensure_loaded(marmot),
    Query = #typed_query{
        input_file_name = "maybe_name.sql",
        starting_line = 1,
        root_name = "maybe_name",
        content = ~"select name from users where id = $1",
        params = [int],
        returns = [#field{identifier = name, type = {option, bit_array}}],
        doc = []
    },
    {ok, Forms} = codegen:forms(maybe_name_sql, [Query]),
    ?assertMatch({ok, _, _}, compile:forms(Forms, [return_errors])).

compile_zero_column_test() ->
    {ok, Forms} = codegen:forms(ping_sql, [ping_query()]),
    ?assertMatch({ok, _, _}, compile:forms(Forms, [return_errors])).

module_starts_with_banner_test() ->
    {ok, Bin} = codegen:module(get_user_sql, [get_user_query()]),
    ?assertEqual(
        ~"%% Code generated by marmot. DO NOT EDIT.\n\n",
        binary:part(Bin, 0, byte_size(~"%% Code generated by marmot. DO NOT EDIT.\n\n"))
    ).

doc_less_query_omits_doc_test() ->
    {ok, Forms} = codegen:forms(ping_sql, [ping_query()]),
    Rendered = codegen:render(Forms),
    ?assertEqual(nomatch, binary:match(Rendered, ~"-doc(")).

duplicate_output_columns_test() ->
    {module, marmot} = code:ensure_loaded(marmot),
    Query = #typed_query{
        input_file_name = "dup.sql",
        starting_line = 1,
        root_name = "dup",
        content = ~"select u.id, o.id from users u, orders o",
        params = [],
        returns = [
            #field{identifier = id, type = int},
            #field{identifier = id, type = int}
        ],
        doc = []
    },
    Result = codegen:forms(dup_sql, [Query]),
    ?assertEqual({error, {duplicate_output_columns, "dup", [id]}}, Result),
    {error, Reason} = Result,
    Message = codegen:format_error(Reason),
    ?assertNotEqual(nomatch, binary:match(Message, ~"id")),
    ?assertNotEqual(nomatch, binary:match(Message, ~"dup")).

enum_conflict_test() ->
    {module, marmot} = code:ensure_loaded(marmot),
    Query1 = #typed_query{
        input_file_name = "q1.sql",
        starting_line = 1,
        root_name = "q1",
        content = ~"select $1::status",
        params = [{enum, {100, ~"status", [~"a"]}}],
        returns = [],
        doc = []
    },
    Query2 = #typed_query{
        input_file_name = "q2.sql",
        starting_line = 1,
        root_name = "q2",
        content = ~"select $1::status",
        params = [{enum, {200, ~"status", [~"b"]}}],
        returns = [],
        doc = []
    },
    Result = codegen:forms(conflict_sql, [Query1, Query2]),
    ?assertEqual({error, {enum_conflict, ~"status", [100, 200]}}, Result),
    {error, Reason} = Result,
    Message = codegen:format_error(Reason),
    ?assertNotEqual(nomatch, binary:match(Message, ~"status")),
    ?assertNotEqual(nomatch, binary:match(Message, ~"100")),
    ?assertNotEqual(nomatch, binary:match(Message, ~"200")).

name_collision_test() ->
    {module, marmot} = code:ensure_loaded(marmot),
    Query1 = #typed_query{
        input_file_name = "foo.sql",
        starting_line = 1,
        root_name = "foo",
        content = ~"select 1",
        params = [],
        returns = [],
        doc = []
    },
    Query2 = #typed_query{
        input_file_name = "foo_sql.sql",
        starting_line = 1,
        root_name = "foo_sql",
        content = ~"select 1",
        params = [],
        returns = [],
        doc = []
    },
    Result = codegen:forms(collide_sql, [Query1, Query2]),
    ?assertEqual({error, {name_collision, foo_sql, 0}}, Result),
    {error, Reason} = Result,
    Message = codegen:format_error(Reason),
    ?assertNotEqual(nomatch, binary:match(Message, ~"foo_sql")).
