-module(codegen).

-import_record(marmot, [typed_query, field]).

-export([module/2, forms/2, render/1, format_error/1]).

-define(BANNER, ~"%% Code generated by marmot. DO NOT EDIT.\n\n").
-define(PRETTYPR_OPTS, [{paper, 96}, {ribbon, 90}]).
-define(MERL_POS, 1).

-spec module(module(), [#typed_query{}]) -> {ok, binary()} | {error, term()}.
module(Module, Queries) ->
    maybe
        {ok, Forms} ?= forms(Module, Queries),
        {ok, <<?BANNER/binary, (render(Forms))/binary>>}
    end.

-spec forms(module(), [#typed_query{}]) ->
    {ok, [erl_parse:abstract_form()]} | {error, term()}.
forms(Module, Queries) ->
    Header = [
        {attribute, codegen_type:anno(), module, Module},
        {attribute, codegen_type:anno(), export, export_list(Queries)}
    ],
    Body = lists:flatmap(fun query_forms/1, Queries),
    {ok, erl_syntax:revert_forms(erl_syntax:form_list(Header ++ Body))}.

-spec render([erl_parse:abstract_form()]) -> binary().
render(Forms) ->
    Formatted = erl_prettypr:format(erl_syntax:form_list(Forms), ?PRETTYPR_OPTS),
    unicode:characters_to_binary(Formatted).

-spec format_error(term()) -> binary().
format_error(Reason) ->
    unicode:characters_to_binary(io_lib:format("~p", [Reason])).

-spec export_list([#typed_query{}]) -> [{atom(), non_neg_integer()}].
export_list(Queries) ->
    lists:flatmap(fun query_exports/1, Queries).

-spec query_exports(#typed_query{}) -> [{atom(), non_neg_integer()}].
query_exports(Query = #typed_query{params = Params}) ->
    [{query_name(Query), length(Params)}, {sql_name(Query), 0}].

-spec query_name(#typed_query{}) -> atom().
query_name(#typed_query{root_name = RootName}) ->
    binary_to_atom(iolist_to_binary(RootName), utf8).

-spec sql_name(#typed_query{}) -> atom().
sql_name(Query) ->
    suffixed_atom(query_name(Query), "_sql").

-spec row_record_name(#typed_query{}) -> atom().
row_record_name(Query) ->
    suffixed_atom(query_name(Query), "_row").

-spec decode_name(#typed_query{}) -> atom().
decode_name(Query) ->
    prefixed_atom("decode_", row_record_name(Query)).

-spec suffixed_atom(atom(), string()) -> atom().
suffixed_atom(Root, Suffix) ->
    list_to_atom(atom_to_list(Root) ++ Suffix).

-spec prefixed_atom(string(), atom()) -> atom().
prefixed_atom(Prefix, Root) ->
    list_to_atom(Prefix ++ atom_to_list(Root)).

-spec query_forms(#typed_query{}) -> [erl_parse:abstract_form() | erl_syntax:syntaxTree()].
query_forms(Query) ->
    record_forms(Query) ++
        [sql_form(Query)] ++
        doc_forms(Query) ++
        [spec_form(Query), function_form(Query)] ++
        decode_forms(Query).

-spec record_forms(#typed_query{}) -> [erl_parse:abstract_form()].
record_forms(#typed_query{returns = []}) ->
    [];
record_forms(Query = #typed_query{returns = Returns}) ->
    RecordName = row_record_name(Query),
    Fields = [
        {typed_record_field,
            {record_field, codegen_type:anno(),
                {atom, codegen_type:anno(), Field#field.identifier}},
            codegen_type:to_ast(Field#field.type)}
     || Field <- Returns
    ],
    [
        {attribute, codegen_type:anno(), native_record, {RecordName, Fields}},
        {attribute, codegen_type:anno(), export_record, [RecordName]}
    ].

-spec sql_form(#typed_query{}) -> erl_syntax:syntaxTree().
sql_form(Query = #typed_query{content = Content}) ->
    Codepoints = unicode:characters_to_list(Content, utf8),
    Bin =
        {bin, codegen_type:anno(), [
            {bin_element, codegen_type:anno(), {string, codegen_type:anno(), Codepoints}, default, [
                utf8
            ]}
        ]},
    merl:qquote(?MERL_POS, "'@Name'() -> _@Sql.", [
        {'Name', term(sql_name(Query))},
        {'Sql', Bin}
    ]).

-spec doc_forms(#typed_query{}) -> [erl_parse:abstract_form()].
doc_forms(#typed_query{doc = []}) ->
    [];
doc_forms(#typed_query{doc = Lines}) ->
    Text = lists:flatten(
        lists:join("\n", [unicode:characters_to_list(Line, utf8) || Line <- Lines])
    ),
    [{attribute, codegen_type:anno(), doc, Text}].

-spec spec_form(#typed_query{}) -> erl_parse:abstract_form().
spec_form(Query = #typed_query{params = Params}) ->
    ParamTypes = [
        {ann_type, codegen_type:anno(), [
            {var, codegen_type:anno(), arg_var_name(I)}, codegen_type:to_ast(P)
        ]}
     || {I, P} <- lists:enumerate(1, Params)
    ],
    {attribute, codegen_type:anno(), spec,
        {{query_name(Query), length(Params)}, [
            {type, codegen_type:anno(), 'fun', [
                {type, codegen_type:anno(), product, ParamTypes},
                return_type(Query)
            ]}
        ]}}.

-spec return_type(#typed_query{}) -> erl_parse:abstract_type().
return_type(#typed_query{returns = []}) ->
    {type, codegen_type:anno(), union, [
        {type, codegen_type:anno(), tuple, [
            {atom, codegen_type:anno(), ok}, {type, codegen_type:anno(), non_neg_integer, []}
        ]},
        {type, codegen_type:anno(), tuple, [
            {atom, codegen_type:anno(), error}, {type, codegen_type:anno(), term, []}
        ]}
    ]};
return_type(Query = #typed_query{}) ->
    RecordName = row_record_name(Query),
    {type, codegen_type:anno(), union, [
        {type, codegen_type:anno(), tuple, [
            {atom, codegen_type:anno(), ok},
            {type, codegen_type:anno(), non_neg_integer, []},
            {type, codegen_type:anno(), list, [
                {type, codegen_type:anno(), record, [{atom, codegen_type:anno(), RecordName}]}
            ]}
        ]},
        {type, codegen_type:anno(), tuple, [
            {atom, codegen_type:anno(), error}, {type, codegen_type:anno(), term, []}
        ]}
    ]}.

-spec function_form(#typed_query{}) -> erl_syntax:syntaxTree().
function_form(Query = #typed_query{params = Params, returns = []}) ->
    merl:qquote(?MERL_POS, zero_column_query_text(), [
        {'Name', term(query_name(Query))},
        {'Args', arg_vars(length(Params))},
        {'SqlName', term(sql_name(Query))}
    ]);
function_form(Query = #typed_query{params = Params}) ->
    merl:qquote(?MERL_POS, query_text(), [
        {'Name', term(query_name(Query))},
        {'Args', arg_vars(length(Params))},
        {'SqlName', term(sql_name(Query))},
        {'DecodeName', term(decode_name(Query))}
    ]).

-spec zero_column_query_text() -> string().
zero_column_query_text() ->
    "'@Name'(_@@Args) ->\n"
    "    Opts = #{decode_opts =>\n"
    "                 [{return_rows_as_maps, false},\n"
    "                  {column_name_as_atom, false},\n"
    "                  {decode_fun, undefined}]},\n"
    "    case pgo:query('@SqlName'(), [_@@Args], Opts) of\n"
    "        #{num_rows := N} -> {ok, N};\n"
    "        {error, _} = E -> E\n"
    "    end.".

-spec query_text() -> string().
query_text() ->
    "'@Name'(_@@Args) ->\n"
    "    Opts = #{decode_opts =>\n"
    "                 [{return_rows_as_maps, false},\n"
    "                  {column_name_as_atom, false},\n"
    "                  {decode_fun, undefined}]},\n"
    "    case pgo:query('@SqlName'(), [_@@Args], Opts) of\n"
    "        #{num_rows := N, rows := Rows} ->\n"
    "            try {ok, N, ['@DecodeName'(R) || R <- Rows]} catch\n"
    "                throw:{marmot_decode_error, Reason} -> {error, Reason}\n"
    "            end;\n"
    "        {error, _} = E -> E\n"
    "    end.".

-spec at_pos(erl_syntax:syntaxTree()) -> erl_syntax:syntaxTree().
at_pos(Tree) ->
    erl_syntax_lib:map(fun(Node) -> erl_syntax:set_pos(Node, ?MERL_POS) end, Tree).

-spec term(term()) -> erl_syntax:syntaxTree().
term(Value) ->
    at_pos(merl:term(Value)).

-spec var(atom()) -> erl_syntax:syntaxTree().
var(Name) ->
    at_pos(merl:var(Name)).

-spec arg_vars(non_neg_integer()) -> [erl_syntax:syntaxTree()].
arg_vars(N) ->
    [var(arg_var_name(I)) || I <- lists:seq(1, N)].

-spec arg_var_name(pos_integer()) -> atom().
arg_var_name(I) ->
    list_to_atom("Arg" ++ integer_to_list(I)).

-spec decode_forms(#typed_query{}) -> [erl_syntax:syntaxTree()].
decode_forms(#typed_query{returns = []}) ->
    [];
decode_forms(Query = #typed_query{returns = Returns}) ->
    Cols = [var(col_var_name(I)) || I <- lists:seq(1, length(Returns))],
    Fields = [field_form(Field, Col) || {Field, Col} <- lists:zip(Returns, Cols)],
    RecordExpr = at_pos(
        erl_syntax:record_expr(erl_syntax:atom(row_record_name(Query)), Fields)
    ),
    [
        merl:qquote(?MERL_POS, "'@DecodeName'({_@@Cols}) -> _@Record.", [
            {'DecodeName', term(decode_name(Query))},
            {'Cols', Cols},
            {'Record', RecordExpr}
        ])
    ].

-spec col_var_name(pos_integer()) -> atom().
col_var_name(I) ->
    list_to_atom("C" ++ integer_to_list(I)).

-spec field_form(#field{}, erl_syntax:syntaxTree()) -> erl_syntax:syntaxTree().
field_form(#field{identifier = Identifier, type = {option, _}}, Col) ->
    Value = merl:qquote(?MERL_POS, "case _@Col of null -> none; V -> {some, V} end", [
        {'Col', Col}
    ]),
    erl_syntax:record_field(erl_syntax:atom(Identifier), Value);
field_form(#field{identifier = Identifier}, Col) ->
    erl_syntax:record_field(erl_syntax:atom(Identifier), Col).
