-module(codegen).

-import_record(marmot, [typed_query, field]).

-export([module/2, forms/2, render/1, format_error/1]).

-define(BANNER, ~"%% Code generated by marmot. DO NOT EDIT.\n\n").
-define(PRETTYPR_OPTS, [{paper, 96}, {ribbon, 90}]).
-define(MERL_POS, 1).

-spec module(module(), [#typed_query{}]) -> {ok, binary()} | {error, term()}.
module(Module, Queries) ->
    maybe
        {ok, Forms} ?= forms(Module, Queries),
        {ok, <<?BANNER/binary, (render(Forms))/binary>>}
    end.

-spec forms(module(), [#typed_query{}]) ->
    {ok, [erl_parse:abstract_form()]} | {error, term()}.
forms(Module, Queries) ->
    maybe
        ok ?= validate(Queries),
        Enums = codegen_type:enums(lists:flatmap(fun query_types/1, Queries)),
        ReturnEnums = return_enums(Queries),
        ParamEnums = param_enums(Queries),
        Header =
            [
                {attribute, codegen_type:anno(), module, Module},
                {attribute, codegen_type:anno(), export, export_list(Queries)}
            ] ++ export_type_forms(Enums) ++ enum_type_forms(Enums),
        Body = lists:flatmap(fun query_forms/1, Queries),
        Guards = guard_forms(Queries),
        EnumCodecs = enum_codec_forms(ReturnEnums, ParamEnums),
        {ok,
            erl_syntax:revert_forms(
                erl_syntax:form_list(Header ++ Body ++ Guards ++ EnumCodecs)
            )}
    end.

-spec render([erl_parse:abstract_form()]) -> binary().
render(Forms) ->
    Formatted = erl_prettypr:format(erl_syntax:form_list(Forms), ?PRETTYPR_OPTS),
    unicode:characters_to_binary(Formatted).

-spec format_error(term()) -> binary().
format_error({duplicate_output_columns, RootName, Identifiers}) ->
    unicode:characters_to_binary(
        io_lib:format(
            "query ~ts has duplicate output column name(s): ~ts. The emitter cannot "
            "generate a record with repeated fields, and the table alias is not "
            "transmitted by Postgres, so marmot cannot rename them for you. Alias one "
            "of the columns in the query, e.g. `select u.id as user_id`.",
            [RootName, lists:join(", ", [atom_to_list(Id) || Id <- Identifiers])]
        )
    );
format_error({enum_conflict, Name, Oids}) ->
    unicode:characters_to_binary(
        io_lib:format(
            "enum ~ts resolves to more than one Postgres type (OIDs ~ts) among the "
            "queries in this module. Two schemas can define same-named enums with "
            "identical variants, and marmot will not silently merge them. Split the "
            "conflicting queries into separate directories so each becomes its own "
            "module; a single query that joins two schemas' same-named enums cannot "
            "currently be split.",
            [Name, lists:join(", ", [integer_to_list(Oid) || Oid <- Oids])]
        )
    );
format_error({name_collision, Name, Arity}) ->
    unicode:characters_to_binary(
        io_lib:format(
            "generated function ~ts/~p would be defined more than once in this "
            "module. Rename the query file or output column that produces it.",
            [Name, Arity]
        )
    );
format_error(Reason) ->
    unicode:characters_to_binary(io_lib:format("~p", [Reason])).

-spec validate([#typed_query{}]) -> ok | {error, term()}.
validate(Queries) ->
    maybe
        ok ?= check_duplicate_output_columns(Queries),
        ok ?= check_enum_conflicts(Queries),
        ok ?= check_name_collisions(Queries)
    end.

-spec check_duplicate_output_columns([#typed_query{}]) -> ok | {error, term()}.
check_duplicate_output_columns([]) ->
    ok;
check_duplicate_output_columns([Query | Rest]) ->
    case duplicate_identifiers(Query#typed_query.returns) of
        [] -> check_duplicate_output_columns(Rest);
        Dupes -> {error, {duplicate_output_columns, Query#typed_query.root_name, Dupes}}
    end.

-spec duplicate_identifiers([#field{}]) -> [atom()].
duplicate_identifiers(Fields) ->
    Counts = lists:foldl(
        fun(#field{identifier = Id}, Acc) ->
            maps:update_with(Id, fun(N) -> N + 1 end, 1, Acc)
        end,
        #{},
        Fields
    ),
    lists:usort([Id || {Id, N} <- maps:to_list(Counts), N > 1]).

-spec check_enum_conflicts([#typed_query{}]) -> ok | {error, term()}.
check_enum_conflicts(Queries) ->
    Types = lists:flatmap(fun query_types/1, Queries),
    Enums = codegen_type:enums(Types),
    case enum_name_conflicts(Enums) of
        [] -> ok;
        [{Name, Oids} | _] -> {error, {enum_conflict, Name, Oids}}
    end.

-spec query_types(#typed_query{}) -> [marmot:type()].
query_types(#typed_query{params = Params, returns = Returns}) ->
    Params ++ [Field#field.type || Field <- Returns].

-spec return_enums([#typed_query{}]) -> [marmot:enum()].
return_enums(Queries) ->
    codegen_type:enums(
        lists:flatmap(
            fun(#typed_query{returns = Returns}) -> [Field#field.type || Field <- Returns] end,
            Queries
        )
    ).

-spec param_enums([#typed_query{}]) -> [marmot:enum()].
param_enums(Queries) ->
    codegen_type:enums(
        lists:flatmap(fun(#typed_query{params = Params}) -> Params end, Queries)
    ).

-spec enum_name_conflicts([marmot:enum()]) -> [{binary(), [pos_integer()]}].
enum_name_conflicts(Enums) ->
    ByName = lists:foldl(
        fun({Oid, Name, _Variants}, Acc) ->
            maps:update_with(Name, fun(Oids) -> [Oid | Oids] end, [Oid], Acc)
        end,
        #{},
        Enums
    ),
    lists:sort([
        {Name, lists:sort(Oids)}
     || {Name, Oids} <- maps:to_list(ByName), length(Oids) > 1
    ]).

-spec check_name_collisions([#typed_query{}]) -> ok | {error, term()}.
check_name_collisions(Queries) ->
    case duplicate_names(emitted_names(Queries)) of
        [] -> ok;
        [{Name, Arity} | _] -> {error, {name_collision, Name, Arity}}
    end.

-spec emitted_names([#typed_query{}]) -> [{atom(), non_neg_integer()}].
emitted_names(Queries) ->
    QueryNames = lists:flatmap(fun query_emitted_names/1, Queries),
    ReturnEnums = return_enums(Queries),
    ParamEnums = param_enums(Queries),
    EnumNames =
        [{enum_decode_fn(Name), 1} || {_Oid, Name, _Variants} <- ReturnEnums] ++
            [{enum_encode_fn(Name), 1} || {_Oid, Name, _Variants} <- ParamEnums],
    QueryNames ++ EnumNames ++ [{assume_not_null, 2}, {array_elem, 2}].

-spec query_emitted_names(#typed_query{}) -> [{atom(), non_neg_integer()}].
query_emitted_names(Query = #typed_query{params = Params, returns = Returns}) ->
    Base = [{query_name(Query), length(Params)}, {sql_name(Query), 0}],
    case Returns of
        [] -> Base;
        _ -> [{decode_name(Query), 1} | Base]
    end.

-spec duplicate_names([{atom(), non_neg_integer()}]) -> [{atom(), non_neg_integer()}].
duplicate_names(Names) ->
    Counts = lists:foldl(
        fun(Key, Acc) -> maps:update_with(Key, fun(N) -> N + 1 end, 1, Acc) end,
        #{},
        Names
    ),
    lists:sort([Key || {Key, N} <- maps:to_list(Counts), N > 1]).

-spec export_list([#typed_query{}]) -> [{atom(), non_neg_integer()}].
export_list(Queries) ->
    lists:flatmap(fun query_exports/1, Queries).

-spec export_type_forms([marmot:enum()]) -> [erl_parse:abstract_form()].
export_type_forms([]) ->
    [];
export_type_forms(Enums) ->
    [
        {attribute, codegen_type:anno(), export_type, [
            {codegen_type:enum_type_name(Name), 0}
         || {_Oid, Name, _Variants} <- Enums
        ]}
    ].

-spec enum_type_forms([marmot:enum()]) -> [erl_parse:abstract_form()].
enum_type_forms(Enums) ->
    [enum_type_form(Enum) || Enum <- Enums].

-spec enum_type_form(marmot:enum()) -> erl_parse:abstract_form().
enum_type_form({_Oid, Name, Variants}) ->
    TypeName = codegen_type:enum_type_name(Name),
    {attribute, codegen_type:anno(), type, {TypeName, enum_union_type(Variants), []}}.

-spec enum_union_type([binary()]) -> erl_parse:abstract_type().
enum_union_type([Variant]) ->
    {atom, codegen_type:anno(), binary_to_atom(Variant, utf8)};
enum_union_type(Variants) ->
    {type, codegen_type:anno(), union, [
        {atom, codegen_type:anno(), binary_to_atom(V, utf8)}
     || V <- Variants
    ]}.

-spec enum_codec_forms([marmot:enum()], [marmot:enum()]) -> [erl_parse:abstract_form()].
enum_codec_forms(ReturnEnums, ParamEnums) ->
    [enum_decode_form(Enum) || Enum <- ReturnEnums] ++
        [enum_encode_form(Enum) || Enum <- ParamEnums].

-spec enum_decode_form(marmot:enum()) -> erl_parse:abstract_form().
enum_decode_form({_Oid, Name, Variants}) ->
    TypeName = codegen_type:enum_type_name(Name),
    FnName = enum_decode_fn(Name),
    Clauses =
        [
            {clause, codegen_type:anno(), [enum_label_bin(V)], [], [
                {atom, codegen_type:anno(), binary_to_atom(V, utf8)}
            ]}
         || V <- Variants
        ] ++ [unknown_enum_label_clause(TypeName)],
    {function, codegen_type:anno(), FnName, 1, Clauses}.

-spec unknown_enum_label_clause(atom()) -> erl_parse:abstract_clause().
unknown_enum_label_clause(TypeName) ->
    V = {var, codegen_type:anno(), 'V'},
    {clause, codegen_type:anno(), [V], [], [
        {call, codegen_type:anno(), {atom, codegen_type:anno(), throw}, [
            {tuple, codegen_type:anno(), [
                {atom, codegen_type:anno(), marmot_decode_error},
                {tuple, codegen_type:anno(), [
                    {atom, codegen_type:anno(), unknown_enum_label},
                    {atom, codegen_type:anno(), TypeName},
                    V
                ]}
            ]}
        ]}
    ]}.

-spec enum_encode_form(marmot:enum()) -> erl_parse:abstract_form().
enum_encode_form({_Oid, Name, Variants}) ->
    FnName = enum_encode_fn(Name),
    Clauses =
        [
            {clause, codegen_type:anno(), [{atom, codegen_type:anno(), binary_to_atom(V, utf8)}],
                [], [enum_label_bin(V)]}
         || V <- Variants
        ],
    {function, codegen_type:anno(), FnName, 1, Clauses}.

-spec enum_label_bin(binary()) -> erl_parse:abstract_expr().
enum_label_bin(Label) ->
    {bin, codegen_type:anno(), [
        {bin_element, codegen_type:anno(), {string, codegen_type:anno(), binary_to_list(Label)},
            default, default}
    ]}.

-spec enum_decode_fn(binary()) -> atom().
enum_decode_fn(Name) ->
    prefixed_atom("to_", codegen_type:enum_type_name(Name)).

-spec enum_encode_fn(binary()) -> atom().
enum_encode_fn(Name) ->
    prefixed_atom("from_", codegen_type:enum_type_name(Name)).

-spec guard_forms([#typed_query{}]) -> [erl_syntax:syntaxTree()].
guard_forms(Queries) ->
    AssumeNotNull =
        case any_assumed_not_null(Queries) of
            true -> [assume_not_null_form()];
            false -> []
        end,
    ArrayElem =
        case any_list_column(Queries) of
            true -> [array_elem_form()];
            false -> []
        end,
    AssumeNotNull ++ ArrayElem.

-spec any_assumed_not_null([#typed_query{}]) -> boolean().
any_assumed_not_null(Queries) ->
    lists:any(
        fun(#typed_query{returns = Returns}) ->
            lists:any(fun(#field{assumed_not_null = Assumed}) -> Assumed end, Returns)
        end,
        Queries
    ).

-spec any_list_column([#typed_query{}]) -> boolean().
any_list_column(Queries) ->
    lists:any(
        fun(#typed_query{returns = Returns}) ->
            lists:any(fun(#field{type = Type}) -> type_has_list(Type) end, Returns)
        end,
        Queries
    ).

-spec type_has_list(marmot:type()) -> boolean().
type_has_list({list, _}) -> true;
type_has_list({option, T}) -> type_has_list(T);
type_has_list(_) -> false.

-spec assume_not_null_form() -> erl_parse:abstract_form().
assume_not_null_form() ->
    Col = {var, codegen_type:anno(), 'Col'},
    Clause1 =
        {clause, codegen_type:anno(), [Col, {atom, codegen_type:anno(), null}], [], [
            {call, codegen_type:anno(), {atom, codegen_type:anno(), throw}, [
                {tuple, codegen_type:anno(), [
                    {atom, codegen_type:anno(), marmot_decode_error},
                    {tuple, codegen_type:anno(), [
                        {atom, codegen_type:anno(), unexpected_null}, Col
                    ]}
                ]}
            ]}
        ]},
    V = {var, codegen_type:anno(), 'V'},
    Clause2 = {clause, codegen_type:anno(), [{var, codegen_type:anno(), '_Col'}, V], [], [V]},
    {function, codegen_type:anno(), assume_not_null, 2, [Clause1, Clause2]}.

-spec array_elem_form() -> erl_parse:abstract_form().
array_elem_form() ->
    Col = {var, codegen_type:anno(), 'Col'},
    Clause1 =
        {clause, codegen_type:anno(), [Col, {atom, codegen_type:anno(), null}], [], [
            {call, codegen_type:anno(), {atom, codegen_type:anno(), throw}, [
                {tuple, codegen_type:anno(), [
                    {atom, codegen_type:anno(), marmot_decode_error},
                    {tuple, codegen_type:anno(), [
                        {atom, codegen_type:anno(), unexpected_null_element}, Col
                    ]}
                ]}
            ]}
        ]},
    Clause2 =
        {clause, codegen_type:anno(),
            [
                Col,
                {tuple, codegen_type:anno(), [
                    {atom, codegen_type:anno(), array}, {var, codegen_type:anno(), '_'}
                ]}
            ],
            [], [
                {call, codegen_type:anno(), {atom, codegen_type:anno(), throw}, [
                    {tuple, codegen_type:anno(), [
                        {atom, codegen_type:anno(), marmot_decode_error},
                        {tuple, codegen_type:anno(), [
                            {atom, codegen_type:anno(), unsupported_multidimensional_array}, Col
                        ]}
                    ]}
                ]}
            ]},
    V = {var, codegen_type:anno(), 'V'},
    Clause3 = {clause, codegen_type:anno(), [{var, codegen_type:anno(), '_Col'}, V], [], [V]},
    {function, codegen_type:anno(), array_elem, 2, [Clause1, Clause2, Clause3]}.

-spec query_exports(#typed_query{}) -> [{atom(), non_neg_integer()}].
query_exports(Query = #typed_query{params = Params}) ->
    [{query_name(Query), length(Params)}, {sql_name(Query), 0}].

-spec query_name(#typed_query{}) -> atom().
query_name(#typed_query{root_name = RootName}) ->
    binary_to_atom(iolist_to_binary(RootName), utf8).

-spec sql_name(#typed_query{}) -> atom().
sql_name(Query) ->
    suffixed_atom(query_name(Query), "_sql").

-spec row_record_name(#typed_query{}) -> atom().
row_record_name(Query) ->
    suffixed_atom(query_name(Query), "_row").

-spec decode_name(#typed_query{}) -> atom().
decode_name(Query) ->
    prefixed_atom("decode_", row_record_name(Query)).

-spec suffixed_atom(atom(), string()) -> atom().
suffixed_atom(Root, Suffix) ->
    list_to_atom(atom_to_list(Root) ++ Suffix).

-spec prefixed_atom(string(), atom()) -> atom().
prefixed_atom(Prefix, Root) ->
    list_to_atom(Prefix ++ atom_to_list(Root)).

-spec query_forms(#typed_query{}) -> [erl_parse:abstract_form() | erl_syntax:syntaxTree()].
query_forms(Query) ->
    record_forms(Query) ++
        [sql_form(Query)] ++
        doc_forms(Query) ++
        [spec_form(Query), function_form(Query)] ++
        decode_forms(Query).

-spec record_forms(#typed_query{}) -> [erl_parse:abstract_form()].
record_forms(#typed_query{returns = []}) ->
    [];
record_forms(Query = #typed_query{returns = Returns}) ->
    RecordName = row_record_name(Query),
    Fields = [
        {typed_record_field,
            {record_field, codegen_type:anno(),
                {atom, codegen_type:anno(), Field#field.identifier}},
            codegen_type:to_ast(Field#field.type)}
     || Field <- Returns
    ],
    [
        {attribute, codegen_type:anno(), native_record, {RecordName, Fields}},
        {attribute, codegen_type:anno(), export_record, [RecordName]}
    ].

-spec sql_form(#typed_query{}) -> erl_syntax:syntaxTree().
sql_form(Query = #typed_query{content = Content}) ->
    Codepoints = unicode:characters_to_list(Content, utf8),
    Bin =
        {bin, codegen_type:anno(), [
            {bin_element, codegen_type:anno(), {string, codegen_type:anno(), Codepoints}, default, [
                utf8
            ]}
        ]},
    merl:qquote(?MERL_POS, "'@Name'() -> _@Sql.", [
        {'Name', term(sql_name(Query))},
        {'Sql', Bin}
    ]).

-spec doc_forms(#typed_query{}) -> [erl_parse:abstract_form()].
doc_forms(#typed_query{doc = []}) ->
    [];
doc_forms(#typed_query{doc = Lines}) ->
    Text = lists:flatten(
        lists:join("\n", [unicode:characters_to_list(Line, utf8) || Line <- Lines])
    ),
    [{attribute, codegen_type:anno(), doc, Text}].

-spec spec_form(#typed_query{}) -> erl_parse:abstract_form().
spec_form(Query = #typed_query{params = Params}) ->
    ParamTypes = [
        {ann_type, codegen_type:anno(), [
            {var, codegen_type:anno(), arg_var_name(I)}, codegen_type:to_ast(P)
        ]}
     || {I, P} <- lists:enumerate(1, Params)
    ],
    {attribute, codegen_type:anno(), spec,
        {{query_name(Query), length(Params)}, [
            {type, codegen_type:anno(), 'fun', [
                {type, codegen_type:anno(), product, ParamTypes},
                return_type(Query)
            ]}
        ]}}.

-spec return_type(#typed_query{}) -> erl_parse:abstract_type().
return_type(#typed_query{returns = []}) ->
    {type, codegen_type:anno(), union, [
        {type, codegen_type:anno(), tuple, [
            {atom, codegen_type:anno(), ok}, {type, codegen_type:anno(), non_neg_integer, []}
        ]},
        {type, codegen_type:anno(), tuple, [
            {atom, codegen_type:anno(), error}, {type, codegen_type:anno(), term, []}
        ]}
    ]};
return_type(Query = #typed_query{}) ->
    RecordName = row_record_name(Query),
    {type, codegen_type:anno(), union, [
        {type, codegen_type:anno(), tuple, [
            {atom, codegen_type:anno(), ok},
            {type, codegen_type:anno(), non_neg_integer, []},
            {type, codegen_type:anno(), list, [
                {type, codegen_type:anno(), record, [{atom, codegen_type:anno(), RecordName}]}
            ]}
        ]},
        {type, codegen_type:anno(), tuple, [
            {atom, codegen_type:anno(), error}, {type, codegen_type:anno(), term, []}
        ]}
    ]}.

-spec function_form(#typed_query{}) -> erl_syntax:syntaxTree().
function_form(Query = #typed_query{params = Params, returns = []}) ->
    ArgVars = arg_vars(length(Params)),
    merl:qquote(?MERL_POS, zero_column_query_text(), [
        {'Name', term(query_name(Query))},
        {'Args', ArgVars},
        {'SqlName', term(sql_name(Query))},
        {'EncodedArgs', encoded_args(Params, ArgVars)}
    ]);
function_form(Query = #typed_query{params = Params}) ->
    ArgVars = arg_vars(length(Params)),
    merl:qquote(?MERL_POS, query_text(), [
        {'Name', term(query_name(Query))},
        {'Args', ArgVars},
        {'SqlName', term(sql_name(Query))},
        {'DecodeName', term(decode_name(Query))},
        {'EncodedArgs', encoded_args(Params, ArgVars)}
    ]).

-spec zero_column_query_text() -> string().
zero_column_query_text() ->
    "'@Name'(_@@Args) ->\n"
    "    Opts = #{decode_opts =>\n"
    "                 [{return_rows_as_maps, false},\n"
    "                  {column_name_as_atom, false},\n"
    "                  {decode_fun, undefined}]},\n"
    "    case pgo:query('@SqlName'(), [_@@EncodedArgs], Opts) of\n"
    "        #{num_rows := N} -> {ok, N};\n"
    "        {error, _} = E -> E\n"
    "    end.".

-spec query_text() -> string().
query_text() ->
    "'@Name'(_@@Args) ->\n"
    "    Opts = #{decode_opts =>\n"
    "                 [{return_rows_as_maps, false},\n"
    "                  {column_name_as_atom, false},\n"
    "                  {decode_fun, undefined}]},\n"
    "    case pgo:query('@SqlName'(), [_@@EncodedArgs], Opts) of\n"
    "        #{num_rows := N, rows := Rows} ->\n"
    "            try {ok, N, ['@DecodeName'(R) || R <- Rows]} catch\n"
    "                throw:{marmot_decode_error, Reason} -> {error, Reason}\n"
    "            end;\n"
    "        {error, _} = E -> E\n"
    "    end.".

-spec at_pos(erl_syntax:syntaxTree()) -> erl_syntax:syntaxTree().
at_pos(Tree) ->
    erl_syntax_lib:map(fun(Node) -> erl_syntax:set_pos(Node, ?MERL_POS) end, Tree).

-spec term(term()) -> erl_syntax:syntaxTree().
term(Value) ->
    at_pos(merl:term(Value)).

-spec var(atom()) -> erl_syntax:syntaxTree().
var(Name) ->
    at_pos(merl:var(Name)).

-spec arg_vars(non_neg_integer()) -> [erl_syntax:syntaxTree()].
arg_vars(N) ->
    [var(arg_var_name(I)) || I <- lists:seq(1, N)].

-spec arg_var_name(pos_integer()) -> atom().
arg_var_name(I) ->
    list_to_atom("Arg" ++ integer_to_list(I)).

-spec encoded_args([marmot:type()], [erl_syntax:syntaxTree()]) -> [erl_syntax:syntaxTree()].
encoded_args(Params, ArgVars) ->
    [encode_param(Param, Var) || {Param, Var} <- lists:zip(Params, ArgVars)].

-spec encode_param(marmot:type(), erl_syntax:syntaxTree()) -> erl_syntax:syntaxTree().
encode_param({enum, {_Oid, Name, _Variants}}, Var) ->
    Fn = enum_encode_fn(Name),
    merl:qquote(?MERL_POS, "'@Fn'(_@Var)", [{'Fn', term(Fn)}, {'Var', Var}]);
encode_param({list, {enum, {_Oid, Name, _Variants}}}, Var) ->
    Fn = enum_encode_fn(Name),
    merl:qquote(?MERL_POS, "['@Fn'(X) || X <- _@Var]", [{'Fn', term(Fn)}, {'Var', Var}]);
encode_param(_Type, Var) ->
    Var.

-spec decode_forms(#typed_query{}) -> [erl_syntax:syntaxTree()].
decode_forms(#typed_query{returns = []}) ->
    [];
decode_forms(Query = #typed_query{returns = Returns}) ->
    Cols = [var(col_var_name(I)) || I <- lists:seq(1, length(Returns))],
    Fields = [field_form(Field, Col) || {Field, Col} <- lists:zip(Returns, Cols)],
    RecordExpr = at_pos(
        erl_syntax:record_expr(erl_syntax:atom(row_record_name(Query)), Fields)
    ),
    [
        merl:qquote(?MERL_POS, "'@DecodeName'({_@@Cols}) -> _@Record.", [
            {'DecodeName', term(decode_name(Query))},
            {'Cols', Cols},
            {'Record', RecordExpr}
        ])
    ].

-spec col_var_name(pos_integer()) -> atom().
col_var_name(I) ->
    list_to_atom("C" ++ integer_to_list(I)).

-spec field_form(#field{}, erl_syntax:syntaxTree()) -> erl_syntax:syntaxTree().
field_form(#field{identifier = Identifier, type = Type, assumed_not_null = Assumed}, Col) ->
    Value = column_value(Type, Assumed, Col, Identifier),
    erl_syntax:record_field(erl_syntax:atom(Identifier), Value).

-spec column_value(marmot:type(), boolean(), erl_syntax:syntaxTree(), atom()) ->
    erl_syntax:syntaxTree().
column_value({option, T}, _Assumed, Col, ColName) ->
    Inner = non_null_value(T, var('V'), ColName),
    merl:qquote(?MERL_POS, "case _@Col of null -> none; V -> {some, _@Inner} end", [
        {'Col', Col}, {'Inner', Inner}
    ]);
column_value(Type, true, Col, ColName) ->
    non_null_value(Type, guarded_col(Col, ColName), ColName);
column_value(Type, false, Col, ColName) ->
    non_null_value(Type, Col, ColName).

-spec guarded_col(erl_syntax:syntaxTree(), atom()) -> erl_syntax:syntaxTree().
guarded_col(Col, ColName) ->
    merl:qquote(?MERL_POS, "assume_not_null(_@ColName, _@Col)", [
        {'ColName', term(ColName)}, {'Col', Col}
    ]).

-spec non_null_value(marmot:type(), erl_syntax:syntaxTree(), atom()) -> erl_syntax:syntaxTree().
non_null_value({enum, {_Oid, Name, _Variants}}, ValueTree, _ColName) ->
    Fn = enum_decode_fn(Name),
    merl:qquote(?MERL_POS, "'@Fn'(_@V)", [{'Fn', term(Fn)}, {'V', ValueTree}]);
non_null_value({list, ElemType}, ValueTree, ColName) ->
    list_value(ElemType, ValueTree, ColName);
non_null_value(_Plain, ValueTree, _ColName) ->
    ValueTree.

-spec list_value(marmot:type(), erl_syntax:syntaxTree(), atom()) -> erl_syntax:syntaxTree().
list_value({enum, {_Oid, Name, _Variants}}, ValueTree, ColName) ->
    Fn = enum_decode_fn(Name),
    merl:qquote(?MERL_POS, "['@Fn'(array_elem(_@ColName, X)) || X <- _@V]", [
        {'Fn', term(Fn)}, {'ColName', term(ColName)}, {'V', ValueTree}
    ]);
list_value(_ElemType, ValueTree, ColName) ->
    merl:qquote(?MERL_POS, "[array_elem(_@ColName, X) || X <- _@V]", [
        {'ColName', term(ColName)}, {'V', ValueTree}
    ]).
