on: push

jobs:
  test:
    runs-on: ubuntu-latest
    name: Erlang/OTP ${{matrix.otp}} / rebar3 ${{matrix.rebar3}}
    strategy:
      matrix:
        otp: ['28.5']
        rebar3: ['3.27.0']
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: erlef/setup-beam@fc68ffb90438ef2936bbb3251622353b3dcb2f93 # v1.24.0
        with:
          otp-version: ${{matrix.otp}}
          rebar3-version: ${{matrix.rebar3}}
      # See https://github.com/ikalnytskyi/action-setup-postgres/issues/40
      - uses: ikalnytskyi/action-setup-postgres@c4dda34aae1c821e3a771b68b73b13af3198a7ee # v8
        id: postgres
        with:
          username: marmot
          password: marmot
          database: marmot
          port: 5432
      # The Erlang files should be formatted
      - run: rebar3 fmt --check
      # Run eunit
      - run: rebar3 eunit
      # Run common test
      - run: rebar3 ct
        env:
          PGO_POOL_SIZE: 1
          PGO_HOST: localhost
          PGO_USER: marmot
          PGO_DATABASE: marmot
          PGO_PASSWORD: marmot
          PGO_PORT: 5432
